version: 1.0.{build}
image: Visual Studio 2017

init:
  - rd /s /q C:\OpenSSL-Win64
  - rd /s /q C:\OpenSSL-Win32

environment:
  ZLIB_DIST_NAME: zlib-1.2.11-static-mt
  OPENSSL_DIST_NAME: openssl-1.1.0h
  BOOST_DIST_NAME: boost-vc141-1_68_0-bin
  DEPS_DIST_URI: https://s3-us-west-2.amazonaws.com/streamlabs-obs-updater-deps/
  DEPS_LOCAL_PATH: C:\projects\slobs-updater-deps
  ZLIB_ROOT: $(DEPS_LOCAL_PATH)\$(ZLIB_DIST_NAME)
  OPENSSL_ROOT: $(DEPS_LOCAL_PATH)\$(OPENSSL_DIST_NAME)
  BOOST_ROOT: $(DEPS_LOCAL_PATH)\$(BOOST_DIST_NAME)
  BUILD_DIR: $(APPVEYOR_BUILD_FOLDER)\build
  SIGN_TOOL: C:\Program Files (x86)\Windows Kits\10\bin\x64\signtool.exe
  STREAMLABS_PFX_SECRET:
    secure: iZlMSWnmH5FQDpa+/0SgXIyvCobkElj2y5lu94Uo8VnTWHTeTC1/bpVkzsLreENocomvDB5ywsa3+QdathRp8A==
  STREAMLABS_SECRET:
    secure: hr+VpykbGiCI5I0ltiqH667wh/YQx2Fi5SBLfkOWHSg=

  matrix:
  - BUILD_TYPE: Release
  - BUILD_TYPE: Debug
  - BUILD_TYPE: MinSizeRel
  - BUILD_TYPE: RelWithDebInfo

install:
  - nuget install secure-file -ExcludeVersion
  - if not exist "%DEPS_LOCAL_PATH%" mkdir "%DEPS_LOCAL_PATH%"
  - ci\appveyor\check_dependency.bat "%ZLIB_DIST_NAME%"
  - ci\appveyor\check_dependency.bat "%OPENSSL_DIST_NAME%"
  - ci\appveyor\check_dependency.bat "%BOOST_DIST_NAME%"
  - set PATH=%DEPS_LOCAL_PATH%;%PATH%

cache:
  - $(ZLIB_ROOT)
  - $(OPENSSL_ROOT)
  - $(BOOST_ROOT)

before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

build_script:
  - ci\appveyor\build.bat

artifacts:
- path: build\$(BUILD_TYPE)\*.exe
- path: build\$(BUILD_TYPE)\*.pdb

before_deploy:
- ps: ci\appveyor\sign_binaries.ps1

deploy:
- provider: GitHub
  auth_token:
    secure: +8bGD9UqEQEmN7arCP20Pdy6knm23HiSom8eMRMMP4xDvd9Eo8dPdsVpzgTavJd4
  artifact: slobs-updater-signed-$(BUILD_TYPE).exe
  force_update: true
  on:
    appveyor_repo_tag: true