version: 1.0.{build}
image: Visual Studio 2017

init:
- cmd: >-
    rd /s /q C:\OpenSSL-Win64

    rd /s /q C:\OpenSSL-Win32

environment:
  ZLIB_DIST_NAME: zlib-1.2.11-static-mt
  OPENSSL_DIST_NAME: openssl-1.1.0h
  BOOST_DIST_NAME: boost-msvc141-1_67_0-all
  DEPS_DIST_URI: https://s3-us-west-2.amazonaws.com/streamlabs-obs-updater-deps/
  DEPS_LOCAL_PATH: C:\projects\slobs-updater-deps
  ZLIB_ROOT: $(DEPS_LOCAL_PATH)\$(ZLIB_DIST_NAME)
  OPENSSL_ROOT: $(DEPS_LOCAL_PATH)\$(OPENSSL_DIST_NAME)
  BOOST_ROOT: $(DEPS_LOCAL_PATH)\$(BOOST_DIST_NAME)
  BUILD_DIR: $(APPVEYOR_BUILD_FOLDER)\build
  WIN_MT: C:\Program Files (x86)\Windows Kits\10\bin\x64\mt.exe
  SIGN_TOOL: C:\Program Files (x86)\Windows Kits\10\bin\x64\signtool.exe
  STREAMLABS_PFX_SECRET:
    secure: iZlMSWnmH5FQDpa+/0SgXIyvCobkElj2y5lu94Uo8VnTWHTeTC1/bpVkzsLreENocomvDB5ywsa3+QdathRp8A==
  STREAMLABS_SECRET:
    secure: hr+VpykbGiCI5I0ltiqH667wh/YQx2Fi5SBLfkOWHSg=

  matrix:
  - BUILD_TYPE: Release
    CC: clang-cl
    CXX: clang-cl

  - BUILD_TYPE: Release
    CC: cl
    CXX: cl

  - BUILD_TYPE: Debug
    CC: clang-cl
    CXX: clang-cl

  - BUILD_TYPE: Debug
    CC: cl
    CXX: cl

  - BUILD_TYPE: MinSizeRel
    CC: clang-cl
    CXX: clang-cl

  - BUILD_TYPE: MinSizeRel
    CC: cl
    CXX: cl

install:
- cmd: >-
    nuget install secure-file -ExcludeVersion

    if not exist "%DEPS_LOCAL_PATH%" mkdir "%DEPS_LOCAL_PATH%"

    ci\appveyor\check_dependency.bat "%ZLIB_DIST_NAME%"

    ci\appveyor\check_dependency.bat "%OPENSSL_DIST_NAME%"

    ci\appveyor\check_dependency.bat "%BOOST_DIST_NAME%"

cache:
- $(ZLIB_ROOT)
- $(FLTK_ROOT)
- $(OPENSSL_ROOT)
- $(BOOST_ROOT)

build_script:
- cmd: >-
    ci\appveyor\build.bat

    if exist "%BUILD_TYPE%\slobs-updater.pdb" appveyor PushArtifact "%BUILD_TYPE%\slobs-updater.pdb"

artifacts:
- path: build\$(BUILD_TYPE)\*.exe

before_deploy:
- ps: ci\appveyor\sign_binaries.ps1

deploy:
- provider: GitHub
  auth_token:
    secure: +8bGD9UqEQEmN7arCP20Pdy6knm23HiSom8eMRMMP4xDvd9Eo8dPdsVpzgTavJd4
  artifact: slobs-updater-signed-$(BUILD_TYPE).exe
  force_update: true
  on:
    appveyor_repo_tag: true